name: Build & Code Quality Checks v3

on:
  pull_request:
    branches: ['v3-production', 'v3-staging']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Build & Code Quality Checks v3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm ci --no-audit
          npm run setup:ci

      - name: Execute quality checks
        run: |
          npm run check:circular -- --scope '@rudderstack/analytics-js' --scope '@rudderstack/analytics-js-plugins'
          npm run check:duplicates -- --scope '@rudderstack/analytics-js' --scope '@rudderstack/analytics-js-plugins'

      - name: Execute security checks
        run: |
          npm run check:security

      - name: Execute bundle size checks
        uses: rudderlabs/github-action-check-size-limit@v2.2.0
        env:
          HUSKY: 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: install
          build_script: check:size:build
          script: echo '[' && npx lerna exec --loglevel=silent --scope=@rudderstack/analytics-js --scope=@rudderstack/analytics-js-plugins -- 'npx size-limit --json && echo ,' && echo '[]\n]'
          is_monorepo: true
