name: tests

on:
  pull_request:
    branches:
      - production
      - production-staging

jobs:
  install-and-test:
    name: install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - name: Jest
        run: npm run test
